version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=gofeed
  redis:
    image: redis:alpine
  accounts_rpc:
    build:
      context: internal
      dockerfile: accounts/Dockerfile
    ports:
      - "127.0.0.1:8082:8082"
    environment:
      SERVER_TO_RUN: grpc
      PORT: 8082
      DB_SOURCE: postgresql://root:secret@postgres:5432/gofeed?sslmode=disable
      TEST_DB_SOURCE: postgresql://root:secret@postgres:5432/gofeed_test?sslmode=disable
      REDIS_HOST: redis:6379
      REDIS_DB: 1
    env_file:
      - internal/accounts/cfg.env
    depends_on:
      - redis
      - postgres
  accounts:
    build:
      context: internal
      dockerfile: accounts/Dockerfile
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      SERVER_TO_RUN: http
      PORT: 8080
      DB_SOURCE: postgresql://root:secret@postgres:5432/gofeed?sslmode=disable
      TEST_DB_SOURCE: postgresql://root:secret@postgres:5432/gofeed_test?sslmode=disable
      REDIS_HOST: redis:6379
      REDIS_DB: 1
    env_file:
      - internal/accounts/cfg.env
    depends_on:
      - redis
      - postgres
  posts:
    build:
      context: internal
      dockerfile: posts/Dockerfile
    ports:
      - "127.0.0.1:8081:8081"
    environment:
      SERVER_TO_RUN: http
      PORT: 8081
      DB_SOURCE: postgresql://root:secret@postgres:5432/gofeed?sslmode=disable
      TEST_DB_SOURCE: postgresql://root:secret@postgres:5432/gofeed_test?sslmode=disable
      REDIS_HOST: redis:6379
      REDIS_DB: 1
    env_file:
      - internal/posts/cfg.env
    depends_on:
      - redis
      - postgres
