// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateAccount(ctx context.Context, arg CreateAccountParams) (*Account, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (*User, error)
	GetAccount(ctx context.Context, username string) (*Account, error)
	GetUser(ctx context.Context, uuid string) (*User, error)
	GetUsersByAccount(ctx context.Context, accountUsername string) ([]*User, error)
}

var _ Querier = (*Queries)(nil)
