// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package sqlc

import (
	"time"
)

type Post struct {
	PostID   int64     `json:"post_id"`
	Content  string    `json:"content"`
	PostedOn time.Time `json:"posted_on"`
	PostedBy string    `json:"posted_by"`
	Score    int32     `json:"score"`
}

type Ratedpost struct {
	PostID     int64  `json:"post_id"`
	Account    string `json:"account"`
	RatedScore int32  `json:"rated_score"`
}
