// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreatePost(ctx context.Context, arg CreatePostParams) (int64, error)
	DeletePost(ctx context.Context, postID int64) error
	ListPosts(ctx context.Context, arg ListPostsParams) ([]*Post, error)
}

var _ Querier = (*Queries)(nil)
